import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/About/About";
import Contact from "../components/Contact/Contact";
import Experience from "../components/Experience/Experience";
import Header from "../components/Header/Header";
import Hero from "../components/Hero/Hero";
import Projects from "../components/Projects/Projects";
import Skills from "../components/Skills/Skills";

const Home: NextPage = () => {
    return (
        <div className=" bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll overflow-x-hidden z-0">
            <Head>
                <title>NTHau Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <section id="hero-section" className="snap-center">
                <Hero />
            </section>

            <section id="about-section" className="snap-center">
                <About />
            </section>

            <section id="experience-section" className="snap-center">
                <Experience />
            </section>

            <section id="skills-section" className="snap-center">
                <Skills />
            </section>

            <section id="projects-section" className="snap-center">
                <Projects />
            </section>

            <section id="contact-section" className="snap-center">
                <Contact />
            </section>
        </div>
    );
};

export default Home;

