import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/About/About";
import Contact from "../components/Contact/Contact";
import Experience from "../components/Experience/Experience";
import Header from "../components/Header/Header";
import Hero from "../components/Hero/Hero";
import Projects from "../components/Projects/Projects";
import Skills from "../components/Skills/Skills";

const Home: NextPage = () => {
    return (
        <div id="home-screen">
            <Head>
                <title>NTHau Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <section id="hero-section">
                <Hero />
            </section>
            {/* 
            <About />

            <Experience />

            <Skills />

            <Projects />

            <Contact /> */}
        </div>
    );
};

export default Home;
